(()=>{
  if(document.querySelector('#maximilian23-widget-host'))return;
  const host=document.createElement('div');host.id='maximilian23-widget-host';document.body.append(host);
  const root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>
    :host{all:initial}*{box-sizing:border-box}.launcher{position:fixed;z-index:2147483000;right:22px;bottom:22px;width:68px;height:68px;border:0;border-radius:50%;padding:5px;background:#073440;box-shadow:0 7px 24px #0007,0 0 0 3px #20ead4;cursor:pointer;transition:.2s;overflow:visible}.launcher:hover{transform:translateY(-3px) scale(1.03)}.launcher img{width:100%;height:100%;object-fit:contain}.tip{position:absolute;right:58px;bottom:54px;width:118px;padding:7px 9px;border-radius:12px 12px 3px 12px;background:#fff;color:#082027;font:700 12px/1.2 system-ui,sans-serif;box-shadow:0 4px 16px #0004}.tip:after{content:"";position:absolute;right:-7px;bottom:3px;border:8px solid transparent;border-left-color:#fff;transform:rotate(18deg)}
    .panel{position:fixed;z-index:2147482999;right:22px;bottom:104px;width:min(390px,calc(100vw - 28px));height:min(570px,calc(100vh - 130px));border:1px solid #2a6470;border-radius:19px;background:#071219;box-shadow:0 14px 55px #000a;overflow:hidden;opacity:0;visibility:hidden;transform:translateY(15px) scale(.97);transform-origin:bottom right;transition:.22s}.open .panel{opacity:1;visibility:visible;transform:none}.panel iframe{width:100%;height:100%;border:0}.close{position:absolute;z-index:2;right:8px;top:8px;width:31px;height:31px;border:1px solid #ffffff44;border-radius:50%;background:#071219cc;color:#fff;font:24px/25px system-ui;cursor:pointer}.open .launcher{box-shadow:0 7px 24px #0007,0 0 0 3px #ffb94b}.open .tip{display:none}
    @media(max-width:520px){.launcher{right:16px;bottom:16px;width:62px;height:62px}.tip{display:none}.panel{inset:12px 12px 90px;width:auto;height:auto;border-radius:16px}}
    @media(prefers-reduced-motion:reduce){.launcher,.panel{transition:none}}
  </style><div class="shell"><section class="panel" role="dialog" aria-label="Conversación con Maximilian 23"><button class="close" aria-label="Cerrar">×</button><iframe title="Habla con Maximilian 23" loading="lazy" data-src="https://maximilian23.com/widget/"></iframe></section><button class="launcher" aria-label="Hablar con Maximilian 23" aria-expanded="false"><span class="tip">¿Te ayudo?</span><img src="https://maximilian23.com/Cabeza.png" alt=""></button></div>`;
  const shell=root.querySelector('.shell'),button=root.querySelector('.launcher'),close=root.querySelector('.close'),frame=root.querySelector('iframe');
  function setOpen(open){shell.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open));if(open&&!frame.src)frame.src=frame.dataset.src;}
  button.addEventListener('click',()=>setOpen(!shell.classList.contains('open')));close.addEventListener('click',()=>setOpen(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')setOpen(false)});
})();
