import{initializeApp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import{getAuth,onAuthStateChanged,signInWithPopup,GoogleAuthProvider,signOut}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,getDocs,setDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js?v=1';
const $=s=>document.querySelector(s),EDITORS=['mmartinezf001@educarex.es','fjboraitab01@educarex.es'],app=initializeApp(firebaseConfig,'meteo-editor'),auth=getAuth(app),db=getFirestore(app),editId=new URLSearchParams(location.search).get('id');let images=[],editorLoaded=false;
const permitted=u=>EDITORS.includes(u?.email?.trim().toLowerCase());
function showLogin(u,text){$('#editorPanel').classList.add('hidden');$('#loginPanel').classList.remove('hidden');$('#authStatus').textContent=text;$('#loginLogoutBtn').classList.toggle('hidden',!u);$('#loginError').textContent=''}
async function showEditor(u){$('#sessionUser').textContent=u.email;if(!editorLoaded){await list();if(editId)await open(editId);editorLoaded=true}$('#loginPanel').classList.add('hidden');$('#editorPanel').classList.remove('hidden')}
function loginFailure(e){if(e.code==='auth/popup-closed-by-user'||e.code==='auth/cancelled-popup-request')return'El acceso se canceló. Puedes intentarlo de nuevo.';if(e.code==='auth/popup-blocked')return'El navegador bloqueó la ventana de Google. Permite ventanas emergentes para maximilian23.com.';if(e.code==='auth/unauthorized-domain')return'Firebase no reconoce maximilian23.com como dominio autorizado.';if(e.code==='auth/network-request-failed')return'No se pudo contactar con Google. Comprueba la conexión e inténtalo de nuevo.';return'No se ha podido acceder con Google. Cierra la sesión mostrada y vuelve a intentarlo.'}
onAuthStateChanged(auth,async u=>{try{if(permitted(u))await showEditor(u);else if(u)showLogin(u,'Hay una sesión abierta con '+u.email+', pero esa cuenta no está autorizada. Ciérrala para entrar con otra.');else showLogin(null,'No hay ninguna sesión iniciada.')}catch(e){console.error(e);editorLoaded=false;const denied=e.code==='permission-denied'||e.code==='firestore/permission-denied';showLogin(u,denied?'La cuenta '+u.email+' está identificada, pero todavía no tiene permiso para leer la redacción.':'La cuenta '+u.email+' está identificada, pero la redacción no pudo conectarse a Firebase.');$('#loginError').textContent=denied?'Permiso de edición rechazado por Firebase.':'Fallo de conexión al cargar las entradas. Puedes reintentar o cerrar la sesión.'}});
$('#googleLogin').onclick=async()=>{const b=$('#googleLogin');b.disabled=true;$('#authStatus').textContent='Abriendo Google para elegir cuenta…';$('#loginError').textContent='';try{let p=new GoogleAuthProvider;p.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,p)}catch(e){console.error(e);$('#loginError').textContent=loginFailure(e)}finally{b.disabled=false}};
async function logout(){try{await signOut(auth);editorLoaded=false;showLogin(null,'Sesión cerrada. Ya puedes entrar con otra cuenta.')}catch(e){console.error(e);$('#loginError').textContent='No se pudo cerrar la sesión. Recarga la página e inténtalo de nuevo.'}}
$('#loginLogoutBtn').onclick=logout;$('#logoutBtn').onclick=logout;$('#newBtn').onclick=clear;
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.command,false,b.dataset.value||null));
$('#linkBtn').onclick=()=>{let u=prompt('Dirección del enlace');if(u&&(u.startsWith('https://')||u.startsWith('http://'))){document.execCommand('createLink',false,u);const a=window.getSelection()?.anchorNode?.parentElement?.closest('a');if(a){a.target='_blank';a.rel='noopener noreferrer'}}};
$('#images').onchange=e=>{let f=[...e.target.files];if(f.length>4){msg('Puedes seleccionar un máximo de 4 imágenes.',1);e.target.value='';return}preview(f.map(URL.createObjectURL))};
const tags=()=>[...new Set($('#tagInput').value.split(',').map(x=>x.trim()).filter(Boolean))].slice(0,20),slug=v=>v.normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
async function imageData(f){let bm=await createImageBitmap(f),max=1400,q=.82;for(let i=0;i<6;i++){let s=Math.min(1,max/bm.width),c=document.createElement('canvas');c.width=Math.round(bm.width*s);c.height=Math.round(bm.height*s);c.getContext('2d').drawImage(bm,0,0,c.width,c.height);let b=await new Promise(r=>c.toBlob(r,'image/webp',q));if(b.size<550000)return new Promise(r=>{let x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(b)});max*=.82;q-=.07}throw Error()}
async function save(status){let title=$('#title').value.trim(),body=$('#bodyEditor').innerHTML.trim();if(!title||!body||!$('#summary').value.trim()||!$('#author').value.trim()||!$('#eventDate').value)return msg('Completa todos los campos.',1);try{msg('Guardando…');let f=[...$('#images').files];if(f.length)images=await Promise.all(f.map(imageData));let id=$('#docId').value||slug(title)+'-'+Date.now().toString(36),ref=doc(db,'meteoBlogPosts',id),old=(await getDoc(ref)).data()||{};await setDoc(ref,{title,summary:$('#summary').value.trim(),author:$('#author').value.trim(),eventDate:$('#eventDate').value,hours:$('#hours').value.trim(),tags:tags(),bodyHtml:body,imageDataUrls:images,imageDataUrl:images[0]||'',status,createdAt:old.createdAt||serverTimestamp(),updatedAt:serverTimestamp(),publishedAt:status==='published'?(old.publishedAt||serverTimestamp()):(old.publishedAt||null)},{merge:true});$('#docId').value=id;$('#deleteBtn').classList.remove('hidden');$('#unpublishBtn').classList.toggle('hidden',status!=='published');msg(status==='published'?'Entrada publicada.':'Borrador guardado.');list()}catch(e){console.error(e);msg('No se ha podido guardar.',1)}}
$('#postForm').onsubmit=e=>{e.preventDefault();save('published')};$('#draftBtn').onclick=()=>save('draft');$('#unpublishBtn').onclick=()=>save('draft');$('#deleteBtn').onclick=async()=>{if(!confirm('¿Eliminar esta entrada?'))return;await deleteDoc(doc(db,'meteoBlogPosts',$('#docId').value));clear();list()};
async function list(){let s=await getDocs(collection(db,'meteoBlogPosts')),a=s.docs.map(d=>({id:d.id,...d.data()}));$('#draftList').innerHTML=a.map(p=>'<button data-id="'+p.id+'"><b>'+p.title+'</b><br><small>'+p.status+' · '+(p.tags||[]).join(', ')+'</small></button>').join('')||'Aún no hay entradas.';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>open(b.dataset.id))}
async function open(id){let p=(await getDoc(doc(db,'meteoBlogPosts',id))).data();$('#docId').value=id;['title','summary','author','eventDate','hours'].forEach(k=>$('#'+k).value=p[k]||'');$('#tagInput').value=(p.tags||[]).join(', ');$('#bodyEditor').innerHTML=p.bodyHtml||'';images=p.imageDataUrls?.length?p.imageDataUrls:(p.imageDataUrl?[p.imageDataUrl]:[]);preview(images);$('#deleteBtn').classList.remove('hidden');$('#unpublishBtn').classList.toggle('hidden',p.status!=='published')}
function preview(a){$('#imagePreview').innerHTML=a.map((u,i)=>'<div><img src="'+u+'" alt="Imagen '+(i+1)+'"><span>'+(i?'Imagen '+(i+1):'Portada')+'</span></div>').join('');$('#imagePreview').classList.toggle('hidden',!a.length)}function clear(){$('#postForm').reset();$('#docId').value='';$('#eventDate').value=new Date().toISOString().slice(0,10);$('#bodyEditor').innerHTML='';images=[];preview([]);$('#deleteBtn').classList.add('hidden');$('#unpublishBtn').classList.add('hidden')}function msg(t,e=0){$('#saveMessage').textContent=t;$('#saveMessage').className='form-message'+(e?' error':'')}clear();
