import{initializeApp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';import{getAuth,onAuthStateChanged,signInWithPopup,GoogleAuthProvider,signOut}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';import{getFirestore,collection,doc,getDoc,getDocs,setDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';import{firebaseConfig}from'./firebase-config.js?v=1';
const $=s=>document.querySelector(s),EDITOR_EMAIL='mmartinezf001@educarex.es',app=initializeApp(firebaseConfig,'cite-editor'),auth=getAuth(app),db=getFirestore(app);let currentImageData='';
onAuthStateChanged(auth,async user=>{if(user?.email?.toLowerCase()===EDITOR_EMAIL){$('#loginPanel').classList.add('hidden');$('#editorPanel').classList.remove('hidden');$('#sessionUser').textContent=user.email;loadList()}else{if(user)await signOut(auth);$('#editorPanel').classList.add('hidden');$('#loginPanel').classList.remove('hidden')}});
$('#googleLogin').onclick=async()=>{try{const p=new GoogleAuthProvider();p.setCustomParameters({login_hint:EDITOR_EMAIL});await signInWithPopup(auth,p)}catch(e){if(e.code!=='auth/popup-closed-by-user')$('#loginError').textContent='No se ha podido acceder con esa cuenta.'}};$('#logoutBtn').onclick=()=>signOut(auth);$('#newBtn').onclick=clear;
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.command,false,b.dataset.value||null);$('#bodyEditor').focus()});$('#linkBtn').onclick=()=>{const u=prompt('Dirección del enlace (https://…)');if(u&&/^https?:\/\//i.test(u))document.execCommand('createLink',false,u)};
$('#image').onchange=e=>{const f=e.target.files[0];if(f){$('#imagePreview').style.backgroundImage=`url("${URL.createObjectURL(f)}")`;$('#imagePreview').classList.remove('hidden')}};$('#draftBtn').onclick=()=>save('draft');$('#postForm').onsubmit=e=>{e.preventDefault();save('published')};$('#unpublishBtn').onclick=()=>changeStatus('draft');$('#deleteBtn').onclick=()=>remove($('#docId').value);
const slug=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80),tags=()=>[...new Set($('#tagInput').value.split(',').map(t=>t.trim()).filter(Boolean))].slice(0,12);
async function imageData(file){const bm=await createImageBitmap(file);let max=1400,q=.82;for(let i=0;i<6;i++){const s=Math.min(1,max/bm.width),c=document.createElement('canvas');c.width=Math.round(bm.width*s);c.height=Math.round(bm.height*s);c.getContext('2d').drawImage(bm,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,'image/webp',q));if(b.size<650000)return new Promise(r=>{const x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(b)});max*=.82;q-=.07}throw Error('image')}
async function save(status){const title=$('#title').value.trim(),body=$('#bodyEditor').innerHTML.trim();if(!title||!$('#author').value.trim()||!$('#summary').value.trim()||!$('#eventDate').value||!body){msg('Completa todos los campos y el contenido.',1);return}try{msg('Guardando…');if($('#image').files[0])currentImageData=await imageData($('#image').files[0]);const id=$('#docId').value||`${slug(title)}-${Date.now().toString(36)}`,ref=doc(db,'citePosts',id),old=(await getDoc(ref)).data()||{},record={title,slug:slug(title),author:$('#author').value.trim(),summary:$('#summary').value.trim(),eventDate:$('#eventDate').value,tags:tags(),bodyHtml:body,imageDataUrl:currentImageData,status,createdAt:old.createdAt||serverTimestamp(),updatedAt:serverTimestamp(),publishedAt:status==='published'?(old.publishedAt||serverTimestamp()):(old.publishedAt||null)};await setDoc(ref,record,{merge:true});$('#docId').value=id;$('#deleteBtn').classList.remove('hidden');$('#unpublishBtn').classList.toggle('hidden',status!=='published');msg(status==='published'?'Entrada publicada.':'Borrador guardado.',0,1);loadList()}catch(e){console.error(e);msg('No se ha podido guardar.',1)}}
async function loadList(){const s=await getDocs(collection(db,'citePosts')),items=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));$('#draftList').innerHTML=items.length?items.map(p=>`<div class="draft-item"><button type="button" data-open="${p.id}"><strong>${escapeHtml(p.title)}</strong><span>${p.status==='published'?'Publicada':'Borrador'} · ${(p.tags||[]).join(', ')}</span></button></div>`).join(''):'<p>Aún no hay entradas.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPost(b.dataset.open))}
async function openPost(id){const p=(await getDoc(doc(db,'citePosts',id))).data();$('#docId').value=id;['title','author','summary','eventDate'].forEach(k=>$(`#${k}`).value=p[k]||'');$('#tagInput').value=(p.tags||[]).join(', ');$('#bodyEditor').innerHTML=p.bodyHtml||'';currentImageData=p.imageDataUrl||'';$('#deleteBtn').classList.remove('hidden');$('#unpublishBtn').classList.toggle('hidden',p.status!=='published');if(currentImageData){$('#imagePreview').style.backgroundImage=`url("${currentImageData}")`;$('#imagePreview').classList.remove('hidden')}scrollTo({top:0,behavior:'smooth'})}
async function changeStatus(status){if(!$('#docId').value)return;await setDoc(doc(db,'citePosts',$('#docId').value),{status,updatedAt:serverTimestamp()},{merge:true});$('#unpublishBtn').classList.add('hidden');msg('La entrada queda guardada como borrador.',0,1);loadList()}
async function remove(id){if(!id||!confirm('¿Eliminar definitivamente esta entrada?'))return;await deleteDoc(doc(db,'citePosts',id));clear();msg('Entrada eliminada.',0,1);loadList()}
function clear(){$('#postForm').reset();$('#docId').value='';$('#eventDate').value=new Date().toISOString().slice(0,10);$('#bodyEditor').innerHTML='';$('#imagePreview').classList.add('hidden');$('#deleteBtn').classList.add('hidden');$('#unpublishBtn').classList.add('hidden');currentImageData='';msg('')}
function msg(t,e=0,s=0){$('#saveMessage').textContent=t;$('#saveMessage').className=`form-message${e?' error':''}${s?' success':''}`}function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}clear();
